name: linux
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set env variables
      uses: ./github/env/
    - run: sudo apt-get update
    - run: sudo apt-get install gcc-aarch64-linux-gnu
    - run: sudo apt-get install xz-utils
    - run: sudo apt-get install device-tree-compiler
    - run: sudo apt-get install bc
    - run: make -j4 build/linux/done/pack
    - run: make -j4 build/linux.image.gz{artifact}
    - run: make -j4 build/linux.modules
    - run: make -j4 build/linux.modules.gz{artifact}
